### ISSUE TITLE
Upvotes/down votes not being saved? 

### ISSUE THREAD

**Issue by theboomr** [liftoff-app/liftoff#34]
It seems that when I vote on posts or comments, once I refresh the page or back out and go back to the page later, my votes don't "stick." Not sure if votes are not getting sent to the server in the first place, or if they are, but the app is not getting the updated value from the server or something.

**Comment by zachatrocity** [comment]
Hmm I just tested this and couldn't reproduce. 

However this is very instance specific. Could be your instance timing out or something. Are you able to reliably recreate this issue?

If so or next time you see it could you see if the same thing happens through your instance ui?

**Comment by theboomr** [comment]
I was able to narrow this down more; my votes do seem to be getting saved, but the UI doesn't color the arrow button appropriately after refreshing. I made a screen recording: https://github.com/liftoff-app/liftoff/assets/12604903/82ec6a3a-c038-4a58-9ee8-3918d33548a8

**Comment by zachatrocity** [comment]
Cool thanks for testing this. Will take a look

**Comment by mykdavies** [comment]
If you vote on a comment and then leave the post and return to it, you can click on "..." > Nerd Stuff for that comment and see that the `my_vote` value is `null`, so it looks like it's not getting picked up from the server correctly. Once you click on upvote again it gets set to `1` as expected and you can see that the server already knew about the vote as the vote count doesn't change (unless you're in a popular thread ;-)

**Comment by DarthVi** [comment]
I have the same problem on the instance lemm.ee; the Liftoff UI doesn't seem to remember my comment upvotes if I leave the comment section and get back into it later. Instead post upvotes are fine and upvotes on other instances (lemmy.ml) are fine too.

**Comment by mykdavies** [comment]
This is resolved for comments.

But it still seems to be an issue for posts: Upvote a post and go into it and the upvote is gone. The server score remains at the correct value so pressing upvote again just changes local state.

**Comment by davidgro** [comment]
It's not resolved for comments either, not until the post is refreshed. Test case: find a post with many comments, upvote one near the bottom, scroll up, scroll down. Vote is hidden. 
Same applies to posts on the feed, they aren't remembered until the feed is refreshed, then new ones are still forgotten.
