### ISSUE TITLE
Remove Lemmur branding (splash screen)

### ISSUE THREAD

**Issue by jordan1776** [liftoff-app/liftoff#57]
### Device info

- OS: Android
- OS version: 11
- Device: Xperia 1 II
- Liftoff version: 0.9.12

### Describe the bug

There are still minor references to Lemmur in app. Most notablely is the splash screen has the Lemmur logo instead of Liftoff logo.

### Steps to reproduce

1. Open app from fresh start
2. See Lemmur logo

### Expected behavior

App should not have Lemmur branding in it 

### Screenshots/Screencasts

![Screenshot_20230625-005825_1](https://github.com/liftoff-app/liftoff/assets/6100101/b332918e-4802-4aee-94fa-40ed6729c673)

### Additional context

There might be more Lemmur references and branding elsewhere but I haven't found it, if it exists.

**Comment by zachatrocity** [comment]
I believe this is the last one lol.. thanks!

**Comment by jordan1776** [comment]
No problem, I really appreciate the work you are putting into this app!

**Comment by zachatrocity** [comment]
Like wise! Thanks for helping test and bringing forth all the great suggestions!

**Comment by zachatrocity** [comment]
This has been fixed in #

**Comment by APraxx** [comment]
For me on android there is still a wrong branding on the splash screen.
@zachatrocity  The PR seems to not have addressed the android/app/src/main/res/drawable-XXX/splash.png files?

**Comment by jordan1776** [comment]
Actually yes, I still see the lemmur logo on the splash on 0.10.3, reopen?

**Comment by zachatrocity** [comment]
How are you guys seeing it? I can't get it to load. I'm seeing our rocket icon when I restart the app

**Comment by jordan1776** [comment]
looks like this for me https://imgur.com/oyvbfUM

**Comment by APraxx** [comment]
I use the apk from Github v0.10.4 maybe that's the reason.
